##
## EPITECH PROJECT, 2023
## B-YEP-400-MPL-4-1-zappy-owen1.bolling
## File description:
## Makefile
##

NAME	=	../zappy_ai

all: $(NAME)

$(NAME):
	cp main.py $(NAME)
	chmod +x $(NAME)

clean:

fclean: clean
	$(RM) $(NAME)

re: fclean all
